language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: macisi528@gmail.com
  api_key:
    secure: QfXR5iKi3JjSF717cSItMNbtS8epO8Kv1NfoK/COrMmlZhEBZHTnu8F2imU9BIy6qnCJi2F9QEjPICZKjrzukLDElsQB0X7U11tXmgg/KqNO3OqNlPvMq6C5LRpbrJDvlpZmwyiXkyf70Fbyt5dPFVykSBa4H7RC5SrdyWl6PriWgB+cm9WOJye6f/cefnmpBUXXvd6zzwkvwhnh3TceTNxCoqUgxSfBzkPK2K+oUZcp0IhC6jpoAJjzUYtlZiPstssdjUBw3B7bKx0kK2KrPtCQZNov0gYUQN6k92tqHkb5zSidpoUvVQyW+WS4GsCqlLGWSQZQYtfUkYI448Gp7p8j/5q/jZuNI4kHP4v0n9PX0QpGVimf81kybuCHkyYT8ly+EZ1PhLO/eXa3HKk4ibuBtg8Nv5osp23QlwdaK2cHnErtoDXFKuxY0SvN47yj2bGzthxCSHyrvL/B5xq8NRDaWT3jKFtETzHlBqnB+jdf0c6yA9ZW9PFVihukN/DM+/E5fP0Mrgu6sa8E2CuPaG/8GDynAaMdgaHyoQNo8dVMyIzojksnF4l8CmrocxpfCkLePB8wQhe87DaMhMEInI/31KOU5mBK1uzF86x1SNI/yPp19CIG9pcJT+j9ZVr1iGzGkuQ7E56BNqsNGMm+e49tGjQygSHIG8WbkOPXaLI=
  on:
    tags: true
    repo: EHDFE/ehdev-configer-spa
